parameters:

services:
  _defaults:
    autowire: true
    autoconfigure: true

  Eldahar\SonarQubeReportBundle\:
    resource: '../../'
    exclude:
      - '../../DependencyInjection/'
      - '../../Entity/'
